### ISSUE TITLE
Add console support

### ISSUE THREAD

**Issue by ShaidenUNI** [ShaidenUNI/Turbo_Super_Solo#4]
Parent issue: #3 

I know that thousandths on STMs get rounded down on console version of the game, but I need to confirm that it doesn't change super gold, super silver and super bronze times before doing anything. Otherwise it will require a lot more effort.

The only exception is map 031, which for some reason has the correct thousandth.

**Comment by ShaidenUNI** [comment]
Well, Gyrule just confirmed, that all medals are calculated based on .xx0 STM time.

![image](https://user-images.githubusercontent.com/47535336/148404712-3240fece-8625-408e-945d-48c1643f10e6.png)

Then this requires a lot more spreadsheeting than anticipated.

**Comment by Griesgott** [comment]
Speed told me the same so yeah more work I guess

**Comment by ShaidenUNI** [comment]
Ok, I have calculated it ([last page of this spreadsheet](https://docs.google.com/spreadsheets/d/1eN6S5oXHpkfU2rwaVW1cQJId_GZTC5LOFKTYjBGenas/edit?usp=sharing)).

Don't know how accurate it is, I tried replicating the rounding down to get the same PC times, but it breaks 16 maps, starting from map 127.

Anyway, will add them tomorrow.

**Comment by Griesgott** [comment]
Are the RTM also rounded down on colsole? If so looks as good as we can get I think. 197 would be .300 STM for console I think but I'm not sure wat it's exact. Also I would bump 197 up a tier and 86 one down for console probably.

**Comment by ShaidenUNI** [comment]
According to Gyrule, RTMs are not actually rounded, so I fixed that. Also changed the tiers.

**Comment by ShaidenUNI** [comment]
Also added thousandths to regular medals while I was at it.

**Comment by Griesgott** [comment]
The 197 is still incorrect. Apart from that I would say you can implement it.

**Comment by Griesgott** [comment]
I don't know what it's exaktly only that .37x was  not enough for me and .298 was. I think I read .30x somewhere

**Comment by ShaidenUNI** [comment]
> The 197 is still incorrect

I won't change for now until I get the correct time.

**Comment by Griesgott** [comment]
.30 is correct. At least it says so in the spreadsheet under the bug section

**Comment by ShaidenUNI** [comment]
That's true, gonna fix that rn

**Comment by ShaidenUNI** [comment]
I believe this can be closed now.
